version: 2.1

orbs:
   node : circleci/node@5.2.0
   heroku: circleci/heroku@0.0.10
jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install -g vite
          name: Install vite
      - run:
          command: npm run build
          name: Build app
      
      - persist_to_workspace:
          root: ~/project
          paths: .


workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main